	# g++ -o main -O3 -pthread  -std=c++11 $(SRCS)
	# clang++ -o main -std=c++11 -stdlib=libc++ -O3 $(SRCS)
SRCS=  z1.cpp functions.cpp controller.cpp genetic.cpp

all:
	g++ -o main -O3 -pthread  -std=c++11 $(SRCS)
clean : 
	rm -rf *.out
