	# g++ -o main -O3 -pthread  -std=c++11 z1.cpp
	# g++ -o main -O3 -pthread  -std=c++11 z1.cpp
SRCS=  z1a.cpp functions.cpp TSPCalculator.cpp controller.cpp

all:
	clang++ -o main -std=c++11 -stdlib=libc++ -O3 $(SRCS)
clean : 
	rm -rf *.out
